apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "externaldns.labels" . | indent 4 }}
  name: {{ template "externaldns.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch