{{- if .Values.admin.ingress.enabled -}}
{{- $fullName := include "powerdns.fullname" . -}}
{{- $svcPort := .Values.admin.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
{{- if .Values.admin.ingress.class }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.admin.ingress.class }}
{{- include "powerdns.ingress.annotations" .Values.admin.ingress.class | indent 4 -}}
{{- end }}
spec:
  rules:
    - host: {{ .Values.admin.ingress.hostname }}.{{ .Values.powerdns.domain }}
      http:
        paths:
          - path: {{ .Values.admin.ingress.path | quote }}
            backend:
              serviceName: {{ $fullName }}-service-admin
              servicePort: {{ $svcPort }}
{{- end }}
